# Generated by Django 5.1.7 on 2025-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('industry_type', models.CharField(choices=[('AgriTech', 'AgriTech'), ('MedTech', 'MedTech'), ('FinTech', 'FinTech'), ('Other', 'Other')], max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('light_intensity', models.FloatField(blank=True, null=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('body_temperature', models.FloatField(blank=True, null=True)),
                ('oxygen_level', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('stock_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_data', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='data_images/')),
            ],
        ),
    ]
